wget  https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/venusaur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/venusaur-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charmander.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charmeleon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charizard.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-x.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-y.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/squirtle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wartortle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blastoise.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blastoise-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/caterpie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/metapod.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/butterfree.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/weedle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kakuna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beedrill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beedrill-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pidgey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pidgeotto.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pidgeot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pidgeot-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rattata.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rattata-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raticate.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raticate-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spearow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fearow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ekans.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arbok.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pikachu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pikachu-lets-go.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raichu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raichu-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandslash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandslash-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-f.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidorina.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidoqueen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-m.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidorino.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nidoking.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clefairy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clefable.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vulpix.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vulpix-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ninetales.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ninetales-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jigglypuff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wigglytuff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zubat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golbat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oddish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gloom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vileplume.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/paras.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/parasect.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/venonat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/venomoth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/diglett.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/diglett-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meowth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meowth-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meowth-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/persian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/persian-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/psyduck.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golduck.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mankey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/primeape.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/growlithe.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arcanine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/poliwag.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/poliwhirl.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/poliwrath.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/abra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kadabra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/alakazam.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/alakazam-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/machop.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/machoke.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/machamp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bellsprout.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/weepinbell.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/victreebel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tentacool.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tentacruel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/geodude.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/geodude-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/graveler.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/graveler-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golem-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ponyta.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ponyta-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rapidash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rapidash-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowpoke.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowpoke-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowbro.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowbro-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowbro-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magnemite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magneton.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/farfetchd.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/farfetchd-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/doduo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dodrio.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dewgong.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grimer.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grimer-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/muk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/muk-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shellder.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cloyster.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gastly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/haunter.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gengar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gengar-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/onix.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drowzee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hypno.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/krabby.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kingler.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/voltorb.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/electrode.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/exeggcute.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/exeggutor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/exeggutor-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cubone.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/marowak.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/marowak-alolan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hitmonlee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hitmonchan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lickitung.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/koffing.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/weezing.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/weezing-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rhyhorn.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rhydon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chansey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tangela.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kangaskhan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kangaskhan-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/horsea.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seadra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/goldeen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seaking.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/staryu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/starmie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mr-mime.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mr-mime-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scyther.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jynx.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/electabuzz.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magmar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pinsir.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pinsir-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tauros.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magikarp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gyarados.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gyarados-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lapras.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ditto.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eevee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eevee-lets-go.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vaporeon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jolteon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/flareon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/porygon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/omanyte.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/omastar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kabuto.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kabutops.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aerodactyl.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aerodactyl-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snorlax.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/articuno.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/articuno-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zapdos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zapdos-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/moltres.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/moltres-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dratini.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dragonair.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dragonite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mewtwo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mewtwo-mega-x.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mewtwo-mega-y.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mew.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chikorita.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bayleef.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meganium.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cyndaquil.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/quilava.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/typhlosion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/totodile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/croconaw.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/feraligatr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sentret.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/furret.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hoothoot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/noctowl.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ledyba.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ledian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spinarak.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ariados.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/crobat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chinchou.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lanturn.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pichu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cleffa.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/igglybuff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/togepi.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/togetic.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/natu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/xatu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mareep.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/flaaffy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ampharos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ampharos-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bellossom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/marill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/azumarill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sudowoodo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/politoed.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hoppip.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skiploom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jumpluff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aipom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sunkern.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sunflora.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yanma.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wooper.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/quagsire.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/espeon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/umbreon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/murkrow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowking.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slowking-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/misdreavus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/unown.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wobbuffet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/girafarig.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pineco.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/forretress.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dunsparce.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gligar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/steelix.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/steelix-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snubbull.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/granbull.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/qwilfish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scizor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scizor-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shuckle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/heracross.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/heracross-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sneasel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/teddiursa.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ursaring.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slugma.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magcargo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swinub.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/piloswine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/corsola.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/corsola-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/remoraid.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/octillery.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/delibird.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mantine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skarmory.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/houndour.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/houndoom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/houndoom-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kingdra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/phanpy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/donphan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/porygon2.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stantler.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/smeargle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tyrogue.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hitmontop.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/smoochum.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/elekid.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magby.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/miltank.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blissey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raikou.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/entei.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/suicune.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/larvitar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pupitar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tyranitar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tyranitar-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lugia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ho-oh.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/celebi.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/treecko.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grovyle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sceptile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sceptile-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/torchic.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/combusken.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blaziken.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blaziken-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mudkip.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/marshtomp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swampert.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swampert-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/poochyena.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mightyena.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zigzagoon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zigzagoon-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/linoone.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/linoone-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wurmple.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/silcoon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beautifly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cascoon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dustox.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lotad.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lombre.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ludicolo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seedot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nuzleaf.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shiftry.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/taillow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swellow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wingull.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pelipper.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ralts.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kirlia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gardevoir.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gardevoir-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/surskit.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/masquerain.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shroomish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/breloom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slakoth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vigoroth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slaking.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nincada.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ninjask.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/whismur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/loudred.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/exploud.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/makuhita.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hariyama.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/azurill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nosepass.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skitty.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/delcatty.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sableye.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sableye-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mawile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mawile-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aron.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lairon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aggron.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aggron-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meditite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/medicham.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/medicham-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/electrike.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/manectric.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/manectric-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/plusle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/minun.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/volbeat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/illumise.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/roselia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gulpin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swalot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/carvanha.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sharpedo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sharpedo-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wailmer.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wailord.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/numel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/camerupt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/camerupt-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/torkoal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spoink.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grumpig.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spinda.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/trapinch.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vibrava.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/flygon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cacnea.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cacturne.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swablu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/altaria.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/altaria-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zangoose.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seviper.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lunatone.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/solrock.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/barboach.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/whiscash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/corphish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/crawdaunt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/baltoy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/claydol.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lileep.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cradily.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/anorith.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/armaldo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/feebas.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/milotic.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/castform.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/castform-sunny.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/castform-rainy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/castform-snowy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kecleon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shuppet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/banette.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/banette-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/duskull.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dusclops.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tropius.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chimecho.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/absol.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/absol-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wynaut.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snorunt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/glalie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/glalie-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spheal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sealeo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/walrein.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clamperl.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/huntail.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gorebyss.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/relicanth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/luvdisc.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bagon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shelgon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/salamence.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/salamence-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beldum.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/metang.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/metagross.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/metagross-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/regirock.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/regice.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/registeel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/latias.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/latias-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/latios.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/latios-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kyogre.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kyogre-primal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/groudon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/groudon-primal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rayquaza.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rayquaza-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jirachi.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deoxys-normal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deoxys-attack.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deoxys-defense.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deoxys-speed.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/turtwig.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grotle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/torterra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chimchar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/monferno.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/infernape.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/piplup.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/prinplup.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/empoleon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/starly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/staravia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/staraptor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bidoof.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bibarel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kricketot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kricketune.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shinx.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/luxio.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/luxray.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/budew.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/roserade.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cranidos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rampardos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shieldon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bastiodon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/burmy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wormadam-plant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wormadam-sandy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wormadam-trash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mothim.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/combee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vespiquen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pachirisu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/buizel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/floatzel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cherubi.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cherrim.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shellos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gastrodon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ambipom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drifloon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drifblim.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/buneary.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lopunny.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lopunny-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mismagius.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/honchkrow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/glameow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/purugly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chingling.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stunky.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skuntank.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bronzor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bronzong.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bonsly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mime-jr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/happiny.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chatot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spiritomb.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gible.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gabite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/garchomp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/garchomp-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/munchlax.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/riolu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lucario.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lucario-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hippopotas.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hippowdon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skorupi.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drapion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/croagunk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toxicroak.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/carnivine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/finneon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lumineon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mantyke.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snover.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/abomasnow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/abomasnow-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/weavile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magnezone.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lickilicky.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rhyperior.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tangrowth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/electivire.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magmortar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/togekiss.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yanmega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/leafeon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/glaceon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gliscor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mamoswine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/porygon-z.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gallade.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gallade-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/probopass.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dusknoir.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/froslass.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom-heat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom-wash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom-frost.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom-fan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rotom-mow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/uxie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mesprit.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/azelf.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dialga.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/palkia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/heatran.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/regigigas.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/giratina-altered.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/giratina-origin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cresselia.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/phione.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/manaphy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darkrai.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shaymin-land.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shaymin-sky.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arceus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/victini.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snivy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/servine.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/serperior.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tepig.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pignite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/emboar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oshawott.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dewott.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/samurott.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/patrat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/watchog.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lillipup.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/herdier.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stoutland.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/purrloin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/liepard.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pansage.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/simisage.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pansear.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/simisear.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/panpour.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/simipour.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/munna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/musharna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pidove.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tranquill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/unfezant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blitzle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zebstrika.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/roggenrola.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/boldore.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gigalith.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/woobat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swoobat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drilbur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/excadrill.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/audino.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/audino-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/timburr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gurdurr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/conkeldurr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tympole.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/palpitoad.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/seismitoad.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/throh.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sawk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sewaddle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swadloon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/leavanny.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/venipede.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/whirlipede.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scolipede.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cottonee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/whimsicott.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/petilil.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lilligant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/basculin-red-striped.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/basculin-blue-striped.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/krokorok.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/krookodile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darumaka.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darumaka-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darmanitan-standard.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darmanitan-zen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darmanitan-galarian-standard.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/darmanitan-galarian-zen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/maractus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dwebble.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/crustle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scraggy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scrafty.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sigilyph.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yamask.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yamask-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cofagrigus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tirtouga.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/carracosta.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/archen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/archeops.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/trubbish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/garbodor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zorua.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zoroark.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/minccino.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cinccino.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gothita.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gothorita.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gothitelle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/solosis.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/duosion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/reuniclus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ducklett.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swanna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vanillite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vanillish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vanilluxe.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deerling.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sawsbuck.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/emolga.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/karrablast.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/escavalier.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/foongus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/amoonguss.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/frillish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jellicent.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/alomomola.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/joltik.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/galvantula.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ferroseed.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ferrothorn.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/klink.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/klang.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/klinklang.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tynamo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eelektrik.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eelektross.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/elgyem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beheeyem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/litwick.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lampent.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chandelure.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/axew.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fraxure.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/haxorus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cubchoo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/beartic.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cryogonal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shelmet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/accelgor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stunfisk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stunfisk-galarian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mienfoo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mienshao.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/druddigon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golett.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golurk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pawniard.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bisharp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bouffalant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rufflet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/braviary.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vullaby.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mandibuzz.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/heatmor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/durant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/deino.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zweilous.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hydreigon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/larvesta.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/volcarona.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cobalion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/terrakion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/virizion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tornadus-incarnate.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tornadus-therian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/thundurus-incarnate.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/thundurus-therian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/reshiram.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zekrom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/landorus-incarnate.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/landorus-therian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kyurem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kyurem-black.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kyurem-white.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/keldeo-ordinary.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/keldeo-resolute.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meloetta-aria.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meloetta-pirouette.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/genesect.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chespin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/quilladin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chesnaught.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fennekin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/braixen.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/delphox.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/froakie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/frogadier.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/greninja.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/greninja-ash.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bunnelby.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/diggersby.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fletchling.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fletchinder.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/talonflame.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scatterbug.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spewpa.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vivillon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/litleo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pyroar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/flabebe.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/floette.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/florges.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skiddo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gogoat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pancham.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pangoro.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/furfrou.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/espurr.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meowstic-male.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meowstic-female.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/honedge.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/doublade.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aegislash-shield.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aegislash-blade.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spritzee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aromatisse.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/swirlix.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/slurpuff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/inkay.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/malamar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/binacle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/barbaracle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skrelp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dragalge.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clauncher.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clawitzer.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/helioptile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/heliolisk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tyrunt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tyrantrum.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/amaura.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/aurorus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sylveon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hawlucha.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dedenne.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/carbink.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/goomy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sliggoo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/goodra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/klefki.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/phantump.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/trevenant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pumpkaboo-average.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pumpkaboo-small.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pumpkaboo-large.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pumpkaboo-super.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gourgeist-average.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gourgeist-small.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gourgeist-large.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gourgeist-super.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bergmite.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/avalugg.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/noibat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/noivern.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/xerneas.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yveltal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zygarde-50.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zygarde-10.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zygarde-complete.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/diancie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/diancie-mega.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hoopa-confined.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hoopa-unbound.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/volcanion.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rowlet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dartrix.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/decidueye.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/litten.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/torracat.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/incineroar.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/popplio.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/brionne.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/primarina.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pikipek.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/trumbeak.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toucannon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yungoos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gumshoos.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grubbin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/charjabug.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/vikavolt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/crabrawler.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/crabominable.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oricorio-baile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oricorio-pom-pom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oricorio-pau.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oricorio-sensu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cutiefly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/ribombee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rockruff.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rockruff-own-tempo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lycanroc-midday.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lycanroc-midnight.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lycanroc-dusk.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wishiwashi-solo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wishiwashi-school.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mareanie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toxapex.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mudbray.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mudsdale.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dewpider.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/araquanid.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/fomantis.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lurantis.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/morelull.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/shiinotic.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/salandit.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/salazzle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stufful.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bewear.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bounsweet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/steenee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tsareena.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/comfey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/oranguru.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/passimian.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wimpod.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/golisopod.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandygast.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/palossand.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pyukumuku.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/type-null.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/silvally.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/minior-meteor.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/minior-core.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/komala.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/turtonator.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/togedemaru.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mimikyu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/bruxish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drampa.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dhelmise.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/jangmo-o.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hakamo-o.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kommo-o.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tapu-koko.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tapu-lele.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tapu-bulu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/tapu-fini.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cosmog.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cosmoem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/solgaleo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/lunala.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nihilego.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/buzzwole.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pheromosa.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/xurkitree.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/celesteela.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kartana.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/guzzlord.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/necrozma.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/necrozma-dusk-mane.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/necrozma-dawn-wings.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/necrozma-ultra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/magearna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/marshadow.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/poipole.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/naganadel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stakataka.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blacephalon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zeraora.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/meltan.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/melmetal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grookey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/thwackey.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rillaboom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/scorbunny.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/raboot.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cinderace.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sobble.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drizzile.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/inteleon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/skwovet.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/greedent.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rookidee.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/corvisquire.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/corviknight.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/blipbug.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dottler.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/orbeetle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/nickit.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/thievul.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/gossifleur.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eldegoss.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/wooloo.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dubwool.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/chewtle.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drednaw.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/yamper.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/boltund.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/rolycoly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/carkol.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/coalossal.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/applin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/flapple.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/appletun.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/silicobra.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sandaconda.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cramorant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arrokuda.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/barraskewda.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toxel.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toxtricity-low-key.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/toxtricity-amped.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sizzlipede.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/centiskorch.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/clobbopus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grapploct.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sinistea.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/polteageist.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hatenna.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hattrem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/hatterene.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/impidimp.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/morgrem.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/grimmsnarl.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/obstagoon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/perrserker.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cursola.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/sirfetchd.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/mr-rime.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/runerigus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/milcery.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/alcremie.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/falinks.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/pincurchin.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/snom.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/frosmoth.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/stonjourner.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eiscue-ice.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eiscue-noice.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/indeedee-male.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/indeedee-female.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/morpeko-full-belly.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/morpeko-hangry.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/cufant.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/copperajah.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dracozolt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arctozolt.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dracovish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/arctovish.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/duraludon.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dreepy.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/drakloak.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/dragapult.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zacian-crowned.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zacian-hero.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zamazenta-crowned.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zamazenta-hero.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eternatus.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/eternatus-eternamax.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/kubfu.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/urshifu-single-strike.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/urshifu-rapid-strike.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/zarude.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/regieleki.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/regidrago.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/glastrier.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/spectrier.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/calyrex.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/calyrex-ice-rider.png
wget  https://img.pokemondb.net/sprites/sword-shield/icon/calyrex-shadow-rider.png
